-- Create diagnoses table
CREATE TABLE IF NOT EXISTS public.diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    diagnosis TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.diagnoses ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own diagnoses."
    ON public.diagnoses FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own diagnoses."
    ON public.diagnoses FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own diagnoses."
    ON public.diagnoses FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own diagnoses."
    ON public.diagnoses FOR DELETE
    USING (auth.uid() = user_id);
